package fr.gestionProjet.entities;
// Generated 17 mai 2021 � 17:31:20 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Departements generated by hbm2java
 */
@Entity
@Table(name = "DEPARTEMENTS", schema = "GESTIONPROJETBACK")
public class Departements implements java.io.Serializable {

	private long iddepartement;
	private String libelle;
	private Set<Employes> employeses = new HashSet<Employes>(0);

	public Departements() {
	}

	public Departements(long iddepartement) {
		this.iddepartement = iddepartement;
	}

	public Departements(long iddepartement, String libelle, Set<Employes> employeses) {
		this.iddepartement = iddepartement;
		this.libelle = libelle;
		this.employeses = employeses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE,generator = "DEPARTEMENTS_SEQ")
	@SequenceGenerator(name = "DEPARTEMENTS_SEQ",sequenceName = "DEPARTEMENTS_SEQ",allocationSize = 1)
	@Column(name = "IDDEPARTEMENT", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIddepartement() {
		return this.iddepartement;
	}

	public void setIddepartement(long iddepartement) {
		this.iddepartement = iddepartement;
	}

	@Column(name = "LIBELLE", length = 20)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "departements")
	public Set<Employes> getEmployeses() {
		return this.employeses;
	}

	public void setEmployeses(Set<Employes> employeses) {
		this.employeses = employeses;
	}

}
