package fr.gestionProjet.entities;
// Generated 17 mai 2021 � 17:31:20 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Employes generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYES", schema = "GESTIONPROJETBACK")
public class Employes implements java.io.Serializable {

	private long idemploye;
	private Departements departements;
	private Roles roles;
	private Projets projets;
	private String mail;
	private String nom;
	private String prenom;
	private String pwd;

	public Employes() {
	}

	public Employes(long idemploye) {
		this.idemploye = idemploye;
	}

	public Employes(long idemploye, Departements departements, Roles roles, Projets projets, String mail, String nom,
			String prenom, String pwd) {
		this.idemploye = idemploye;
		this.departements = departements;
		this.roles = roles;
		this.projets = projets;
		this.mail = mail;
		this.nom = nom;
		this.prenom = prenom;
		this.pwd = pwd;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE,generator = "EMPLOYES_SEQ")
	@SequenceGenerator(name = "EMPLOYES_SEQ",sequenceName = "EMPLOYES_SEQ",allocationSize = 1)
	@Column(name = "IDEMPLOYE", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdemploye() {
		return this.idemploye;
	}

	public void setIdemploye(long idemploye) {
		this.idemploye = idemploye;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "IDDEP")
	public Departements getDepartements() {
		return this.departements;
	}

	public void setDepartements(Departements departements) {
		this.departements = departements;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "IDROLE")
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "IDPROJ")
	public Projets getProjets() {
		return this.projets;
	}

	public void setProjets(Projets projets) {
		this.projets = projets;
	}

	@Column(name = "MAIL")
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "NOM")
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM")
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "PWD")
	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

}
