package fr.gestionProjet.entities;
// Generated 17 mai 2021 � 17:31:20 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Modules generated by hbm2java
 */
@Entity
@Table(name = "MODULES", schema = "GESTIONPROJETBACK")
public class Modules implements java.io.Serializable {

	private long idmodule;
	private Projets projets;
	private Date datedebut;
	private Date datefinestimee;
	private Date datefinreel;
	private String nom;
	private Set<Taches> taches = new HashSet<Taches>(0);

	public Modules() {
	}

	public Modules(long idmodule) {
		this.idmodule = idmodule;
	}

	public Modules(long idmodule, Projets projets, Date datedebut, Date datefinestimee, Date datefinreel, String nom,
			Set<Taches> tacheses) {
		this.idmodule = idmodule;
		this.projets = projets;
		this.datedebut = datedebut;
		this.datefinestimee = datefinestimee;
		this.datefinreel = datefinreel;
		this.nom = nom;
		this.taches = taches;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE,generator = "MODULES_SEQ")
	@SequenceGenerator(name = "MODULES_SEQ",sequenceName = "MODULES_SEQ",allocationSize = 1)
	@Column(name = "IDMODULE", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdmodule() {
		return this.idmodule;
	}

	public void setIdmodule(long idmodule) {
		this.idmodule = idmodule;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "FKMODPROJ")
	public Projets getProjets() {
		return this.projets;
	}

	public void setProjets(Projets projets) {
		this.projets = projets;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEDEBUT", length = 7)
	public Date getDatedebut() {
		return this.datedebut;
	}

	public void setDatedebut(Date datedebut) {
		this.datedebut = datedebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEFINESTIMEE", length = 7)
	public Date getDatefinestimee() {
		return this.datefinestimee;
	}

	public void setDatefinestimee(Date datefinestimee) {
		this.datefinestimee = datefinestimee;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEFINREEL", length = 7)
	public Date getDatefinreel() {
		return this.datefinreel;
	}

	public void setDatefinreel(Date datefinreel) {
		this.datefinreel = datefinreel;
	}

	@Column(name = "NOM")
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modules")
	public Set<Taches> getTaches() {
		return this.taches;
	}

	public void setTacheses(Set<Taches> taches) {
		this.taches = taches;
	}

}
