package fr.gestionProjet.entities;
// Generated 17 mai 2021 � 17:31:20 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Projets generated by hbm2java
 */
@Entity
@Table(name = "PROJETS", schema = "GESTIONPROJETBACK")
public class Projets implements java.io.Serializable {

	private long idprojet;
	private String client;
	private Long code;
	private Date datedebut;
	private Date datefinestimee;
	private Date datefinreel;
	private String description;
	private String titre;
	private String type;
	private Set<Employes> employeses = new HashSet<Employes>(0);
	private Set<Modules> moduleses = new HashSet<Modules>(0);

	public Projets() {
	}

	public Projets(long idprojet) {
		this.idprojet = idprojet;
	}

	public Projets(long idprojet, String client, Long code, Date datedebut, Date datefinestimee, Date datefinreel,
			String description, String titre, String type, Set<Employes> employeses, Set<Modules> moduleses) {
		this.idprojet = idprojet;
		this.client = client;
		this.code = code;
		this.datedebut = datedebut;
		this.datefinestimee = datefinestimee;
		this.datefinreel = datefinreel;
		this.description = description;
		this.titre = titre;
		this.type = type;
		this.employeses = employeses;
		this.moduleses = moduleses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE,generator = "PROJETS_SEQ")
	@SequenceGenerator(name = "PROJETS_SEQ",sequenceName = "PROJETS_SEQ",allocationSize = 1)
	@Column(name = "IDPROJET", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdprojet() {
		return this.idprojet;
	}

	public void setIdprojet(long idprojet) {
		this.idprojet = idprojet;
	}

	@Column(name = "CLIENT")
	public String getClient() {
		return this.client;
	}

	public void setClient(String client) {
		this.client = client;
	}

	@Column(name = "CODE", precision = 10, scale = 0)
	public Long getCode() {
		return this.code;
	}

	public void setCode(Long code) {
		this.code = code;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEDEBUT", length = 7)
	public Date getDatedebut() {
		return this.datedebut;
	}

	public void setDatedebut(Date datedebut) {
		this.datedebut = datedebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEFINESTIMEE", length = 7)
	public Date getDatefinestimee() {
		return this.datefinestimee;
	}

	public void setDatefinestimee(Date datefinestimee) {
		this.datefinestimee = datefinestimee;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEFINREEL", length = 7)
	public Date getDatefinreel() {
		return this.datefinreel;
	}

	public void setDatefinreel(Date datefinreel) {
		this.datefinreel = datefinreel;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "TITRE")
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	@Column(name = "TYPE")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "projets")
	public Set<Employes> getEmployeses() {
		return this.employeses;
	}

	public void setEmployeses(Set<Employes> employeses) {
		this.employeses = employeses;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "projets")
	public Set<Modules> getModuleses() {
		return this.moduleses;
	}

	public void setModuleses(Set<Modules> moduleses) {
		this.moduleses = moduleses;
	}

}
