package fr.gestionProjet.entities;
// Generated 17 mai 2021 � 17:31:20 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "ROLES", schema = "GESTIONPROJETBACK")
public class Roles implements java.io.Serializable {

	private long idrole;
	private String libelle;
	private Set<Employes> employeses = new HashSet<Employes>(0);

	public Roles() {
	}

	public Roles(long idrole) {
		this.idrole = idrole;
	}

	public Roles(long idrole, String libelle, Set<Employes> employeses) {
		this.idrole = idrole;
		this.libelle = libelle;
		this.employeses = employeses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE,generator = "ROLES_SEQ")
	@SequenceGenerator(name = "ROLES_SEQ",sequenceName = "ROLES_SEQ",allocationSize = 1)
	@Column(name = "IDROLE", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdrole() {
		return this.idrole;
	}

	public void setIdrole(long idrole) {
		this.idrole = idrole;
	}

	@Column(name = "LIBELLE")
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "roles")
	public Set<Employes> getEmployeses() {
		return this.employeses;
	}

	public void setEmployeses(Set<Employes> employeses) {
		this.employeses = employeses;
	}

}
