package fr.gestionProjet.entities;
// Generated 17 mai 2021 � 17:31:20 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Taches generated by hbm2java
 */
@Entity
@Table(name = "TACHES", schema = "GESTIONPROJETBACK")
public class Taches implements java.io.Serializable {

	private long idtache;
	private Modules modules;
	private Date datedebut;
	private Date datefinestimee;
	private Date datefinreel;
	private String libelle;

	public Taches() {
	}

	public Taches(long idtache) {
		this.idtache = idtache;
	}

	public Taches(long idtache, Modules modules, Date datedebut, Date datefinestimee, Date datefinreel,
			String libelle) {
		this.idtache = idtache;
		this.modules = modules;
		this.datedebut = datedebut;
		this.datefinestimee = datefinestimee;
		this.datefinreel = datefinreel;
		this.libelle = libelle;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE,generator = "TACHES_SEQ")
	@SequenceGenerator(name = "TACHES_SEQ",sequenceName = "TACHES_SEQ",allocationSize = 1)
	@Column(name = "IDTACHE", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdtache() {
		return this.idtache;
	}

	public void setIdtache(long idtache) {
		this.idtache = idtache;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "FKTACHMODU")
	public Modules getModules() {
		return this.modules;
	}

	public void setModules(Modules modules) {
		this.modules = modules;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEDEBUT", length = 7)
	public Date getDatedebut() {
		return this.datedebut;
	}

	public void setDatedebut(Date datedebut) {
		this.datedebut = datedebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEFINESTIMEE", length = 7)
	public Date getDatefinestimee() {
		return this.datefinestimee;
	}

	public void setDatefinestimee(Date datefinestimee) {
		this.datefinestimee = datefinestimee;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEFINREEL", length = 7)
	public Date getDatefinreel() {
		return this.datefinreel;
	}

	public void setDatefinreel(Date datefinreel) {
		this.datefinreel = datefinreel;
	}

	@Column(name = "LIBELLE")
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

}
